controller_joint_names: ['', 'rear_left_hip_joint', 'rear_left_wheel_joint', 'rear_right_hip_joint', 'rear_right_wheel_joint', 'front_left_hip_joint', 'front_left_wheel_joint', 'front_right_hip_joint', 'front_right_wheel_joint', ]
